Stage1
AMikhnyuk/study_project pull request #1
Opened 2021-10-08 21:53 UTC by AMikhnyuk

2021-10-11 08:18 UTC, tsemashko commented on sources/views/activities.js
> +						const month = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
можно через webix.Date.dateToStr проще сделать

2021-10-11 08:18 UTC, tsemashko commented on sources/views/activities.js
> +									template: "#FirstName# #LastName#"
у меня почему-то для contacts отображаются 4 элемента undefined, проверь у себя пожалуйста

2021-10-11 08:18 UTC, tsemashko commented on sources/views/activities.js
> +						this.ui(ActWindowView).showWindow();
ты на каждый клик по этой кнопке add и по кнопкам edit в таблице создаешь новое окно, и при закрытии не удаляешь

2021-10-11 11:14 UTC, kullias commented on sources/views/activities.js
> +									template: "#FirstName# #LastName#"
на моей базе нет, кстати

2021-10-11 12:06 UTC, kullias requested changes

2021-10-11 12:06 UTC, kullias commented on sources/models/collections.js
> +export const contactsCollection = new webix.DataCollection({
каждая модель должна быть в отдельном файле

2021-10-11 12:06 UTC, kullias commented on sources/myapp.js
> +			debug: true,
можно было не менять, оно тру

2021-10-11 12:06 UTC, kullias commented on sources/myapp.js
стоит обработать событие error:resolve
сейчас кликаешь на settings - и падает ошибка
ошибку стоит обрабатывать, поскольку используется тот роутер, с которым структуру приложения менять можно через адресную строку. т.е. ошибку такую легко вызвать.
стоит перенаправлять на какую-то страницу (например на контакты, раз она первая)

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +						this.app.callEvent("addWindow");
ты уже сделал коммуникацию между этим вью и окном через метод
нет надобности в событии. передавай строку в метод

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +					id: "checkbox", width: 40, header: "", template: "{common.checkbox()}"
id взято не из данных, потому нормально не сохраняется (чекни что-то а потом обнови страницу)

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +						suggest: {
https://snippet.webix.com/qthiy660 - общий пример из доки, как разбираться с опциями для колонок, редакторов и фильтров
тут в этой колонке фильтрация и отображение в основном работают, но пустой айтем фильтрацию сбрасывать должен, а он фильтрует по чему-то (по пустому значению, судя по всему)

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +									template: "#FirstName# #LastName#"
да, тут undefined, я сначала не на то подумала
общий пример что делать с опциями для колонок, редакторов и фильтров https://snippet.webix.com/qthiy660

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +					this.app.callEvent("editWindow", [item.row]);
аналогично в комментариями выше:
- плодятся окна
- событие не нужно

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +				table.refresh();
а зачем рефреш?
достаточно просто table.sync(activitiesCollection); переместить сюда

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +	}
если отфильтровать таблицу, а потом что-то в ней поменять, фильтрация сбивается:
- в фильтрах выбрано значение
- данные не отфильтрованы

2021-10-11 12:06 UTC, kullias commented on sources/views/activities.js
> +						return `${ObjDate.getDate()} ${month[ObjDate.getMonth()]} ${ObjDate.getFullYear()}`;
после добавления NaN undefined NaN в колонке с датой, если ничего не выбрать

2021-10-11 12:06 UTC, kullias commented on sources/views/activities_window.js
> +								template({Value}) {
можно покороче template:"#Value#"

2021-10-11 12:06 UTC, kullias commented on sources/views/activities_window.js
> +							{view: "datepicker", label: "Time", type: "time", name: "Time"}
можно выбрать время, не выбрать дату, и в таблице потом будет NaN undefined NaN
в базу уходит 
```
Date: NaN-NaN-NaN NaN:NaN:NaN
Time: NaN-NaN-NaN NaN:NaN:NaN
checkbox: 0
DueDate:  21:57
ObjDate: NaN-NaN-NaN NaN:NaN:NaN
```

то же происходит, если сбросить дату, но оставить время (редактирование)

2021-10-11 12:06 UTC, kullias commented on sources/views/activities_window.js
> +		this.on(this.app, "editWindow", (id) => {
см. комменты выше: события не нужны

2021-10-11 12:06 UTC, kullias commented on sources/views/contacts.js
> +				list.refresh();
опять же. рефреш не надо. достаточно раз сделать синк прямо тут

2021-10-11 12:06 UTC, kullias commented on sources/views/top.js
> -		this.use(plugins.Menu, "top:menu");
раз ты не используешь плагин, придется вручную восстанавливать селект в листе (сейчас нет селекта ни на старте, ни на рефреше).
но можно и плагин использовать

2021-10-11 12:06 UTC, kullias commented on sources/views/top.js
> +			click: (id) => {
лучше onAfterSelect
не будет повторных вызовов для уже выбранного, если кто-то будет кликать

2021-10-11 12:06 UTC, kullias commented on sources/views/top.js
> +				this.show(`${id}`);
можно просто show(id), это уже строка

2021-10-11 12:06 UTC, kullias commented on sources/views/top.js
> +			template: "Hello"
по ТЗ должно отображать название текущей "вкладки"

2021-10-11 16:51 UTC, kullias requested changes

2021-10-11 16:51 UTC, kullias commented on sources/views/activities.js
> +						this.ui(ActWindowView).showWindow("Add");
this.ui() каждый раз создает новое окно

традиционнный подход ко всему этому делу:
- в init() создать окно
- там где надо его показывать
- скрывать окно через hide()

2021-10-11 16:51 UTC, kullias commented on sources/views/activities.js
> +					this.ui(ActWindowView).showWindow("Edit", item.row);
см коммент выше

2021-10-11 16:51 UTC, kullias commented on sources/views/activities_window.js
> +									this.getRoot().close();
см коммент выше

2021-10-11 16:51 UTC, kullias commented on sources/views/activities_window.js
> +										this.getRoot().close();
см коммент выше

2021-10-11 16:51 UTC, kullias commented on sources/views/top.js
> +		this.app.show("/top/contacts");
хитро, но это всё не очень хорошо
вторая строка не нужна. первая делает все (селект -> смена урла)
однако то, что рефреш с урлом top/activities переносит нас на top/contacts - это странно, я бы сказала
отсюда вопрос: почему не использовать плагин меню?

2021-10-11 19:56 UTC, tsemashko approved these changes

2021-10-12 07:24 UTC, kullias approved these changes

2021-10-12 07:35 UTC, merged