Stage2
AMikhnyuk/study_project pull request #2
Opened 2021-10-14 01:00 UTC by AMikhnyuk

2021-10-14 13:34 UTC, kullias requested changes

2021-10-14 13:34 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					if (id)view.filter("#ContactID#", id);
если отфильтровать по встроенному фильтру, эта фильтрация сбросится
как было до:
![Selection_999(294)](https://user-images.githubusercontent.com/31205423/137303503-38394313-5720-4585-b092-7b8d553d0ccf.png)

как стало после:
![Selection_999(293)](https://user-images.githubusercontent.com/31205423/137303548-ed2af428-8d57-482e-89d1-83c01fd08f5d.png)

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +									template: '<img src="#src#" class="form_image">',
![Selection_999(297)](https://user-images.githubusercontent.com/31205423/137304788-e1b772a9-a296-4987-b945-6e7fd75d4ddd.png)
лучше наверное какой-то плейсхолдер сделать типа

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +									template: '<img src="#src#" class="form_image">',
еще не смотрела к чему, но форма всегда кидает это
![Selection_999(296)](https://user-images.githubusercontent.com/31205423/137304887-49da3f6d-4f5e-4a02-8f1c-cb3a5507418b.png)

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/details.js
> +                                        </div>
![Selection_999(298)](https://user-images.githubusercontent.com/31205423/137309221-a68f7f67-b661-457a-9d33-11ad614d717c.png)
думаю стоит добавить какие-то плейсхолдеры минимальные вроде no status

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +										{view: "button", value: "Delete photo"}
стоит тоже сделать рабочей

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +								formValues.Birthday = dateFormat(formValues.Birthday);
![Selection_999(299)](https://user-images.githubusercontent.com/31205423/137314856-9071c914-c019-4d07-a004-2b7eda1f5c17.png)
формат обеих дат оно снова хочет без секунд
![Selection_999(300)](https://user-images.githubusercontent.com/31205423/137315184-d42f98af-dbd5-4bfb-b6fa-445311bd1280.png)
а по текущей строке из например 14 октября 2021 получается 01 Jan 2001 (можно увидеть например если обновить страницу) или посмотреть в терминал с бэком (`"start_date" = '0001-01-01 00:00:00'`)

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/details.js
> +                                        </div>
![Selection_999(301)](https://user-images.githubusercontent.com/31205423/137318294-b4186f57-61c2-4200-b09d-521b5162764d.png)
еще хорошая практика предусматривать такое и ограничивать длину видимой строки + ...

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/details.js
> +                                        </div>
хорошая и простая вещь для всех элементов с фотками - object-fit: cover;

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/details.js
> +				delete_btn: () => {
все функции длиннее 2 строк стоит выносить из конфига в методы класса, а то конфиг растяяягивается и читать все сложнее

2021-10-14 13:34 UTC, kullias commented on sources/views/activitiesViews/table.js
> +								template: (obj) => {
темплейты тоже можно в методы класса выносить

2021-10-14 13:34 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					if (id)view.filter("#ContactID#", id);
Можно так сделать (синхронизация + дофильтровать через апи)
https://snippet.webix.com/bsbez8ta
onAfterFilter вызывается только для табличных фильтров

А можно фильтровать саму коллекцию activities, тогда данные в таблицу сразу попадут ограниченные - но это потребует расфильтровать её на странице Activities

2021-10-14 13:34 UTC, kullias commented on sources/views/activitiesViews/window.js
> +import contactsCollection from "../../models/contactsCollection";
а можно просто "models/ ...." и тогда не надо каждый раз при переносе менять точки

2021-10-14 13:34 UTC, kullias commented on sources/views/contacts.js
> +					this.show(`/top/contacts/contactsViews.details?id=${id}`);
а почему не `this.show(`contactsViews.details?id=${id}`);` ?

2021-10-14 13:34 UTC, kullias commented on sources/views/contacts.js
> +				this.show("/top/contacts/contactsViews.form");
this.show("contactsViews.form"); ?

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/details.js
> +					const id = this.$$("contactsDetails").getValues().id;
а ее из параметра урла еще можно взять (и вообще на урл чейндже сохранить в this.id/contactId например)

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/details.js
> +					this.show(`/top/contacts/contactsViews.form?id=${id}`);
тоже почему не относительный путь?

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/details.js
> +				const table = view.queryView({view: "datatable"});
не очень хорошее дело лезть к виджетам внутри других вью, пусть они и дети этого вью. если ты в какой-то момент решишь что тебе надо не дататейбл, а тритейбл, этот код тоже надо менять... уж лучше сделать конструктор у вью с таблицей, передать ему параметр какой булев и по нему решать показывать ли колонку (при этом ее можно в конфиге сплайсом добавлять по этому параметру,необязательно через hideColumn)

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/files.js
> +				remove: (e, item) => {
в метод класса стоит вынести

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/files.js
> +						const id = this.getParam("id");
тоже можно сохранять в переменную класса (пропертю) эту айдишку

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/files.js
> +					file.ContactID = this.getParam("id");
тоже можно будет тогда брать из this.contactId

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/files.js
> +					file.ContactID = this.getParam("id");
ну и функцию стоит в метод вынести

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +						{view: "text", label: "First name", name: "FirstName"},
вообще какое-то поле с именем не мешало бы сделать обязательным, а то потом имя в дропдаун листах фильтров и ричселектов никакое не отображается

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +													let file = upload.file;
в метод

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +								formValues.Birthday = dateFormat(formValues.Birthday);
и вообще всю функцию в метод стоит

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +								if (contactsCollection.getItem(formValues.id)) {
exists() ?

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +				if (contactsCollection.getItem(id)) {
exists()?

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +					const item = contactsCollection.getItem(id);
а то тут опять гет айтем

2021-10-14 13:34 UTC, kullias commented on sources/views/contactsViews/form.js
> +				if (contactsCollection.getItem(id)) {
или перед этим сохранить в const item

2021-10-15 07:10 UTC, tsemashko commented on sources/views/contactsViews/files.js
> +			autoHeight: true,
лишнее. свойства autoHeight нет, есть autoheight, так что оно ни на что не повлияло

2021-10-15 07:10 UTC, tsemashko commented on sources/views/contactsViews/form.js
> +													let reader = new FileReader();
опять же зачем let?

2021-10-15 07:10 UTC, tsemashko commented on sources/views/contactsViews/details.js
> +				if (contactsCollection.getItem(id)) {
тут getItem получаешь 2 раза, либо вынеси, либо в условии exists используй

2021-10-15 07:10 UTC, tsemashko commented on sources/views/contactsViews/details.js
> +						this.app.callEvent("cancel");
немного режет глаза название ивента cancel в тех местах, где происходит не cancel

2021-10-15 16:11 UTC, kullias requested changes

2021-10-15 16:11 UTC, kullias commented on sources/views/contactsViews/form.js
>  		const contactsForm = {
заметила еще одну мелкую штуку:
- открываем форму на редактирование
- кликаем add contact
- в форме все сбрасывается, но фотка старая остается

2021-10-15 16:11 UTC, kullias commented on sources/views/activitiesViews/table.js
>  				view.hideOverlay();
showOverlay тогда тоже надо, пожалуй, в urlChange

2021-10-15 16:11 UTC, kullias commented on sources/views/contactsViews/files.js
>  					filesCollection.add({...file});
несколько просмотрела, что сортировка по размеру файла - как строки
стоит как числа (в объектах размер как раз хранится и как строка нужного формата и как число)

2021-10-15 16:11 UTC, kullias commented on sources/views/contactsViews/form.js
> +						{view: "text", label: "First name", name: "FirstName", invalidMessage: "Is not be empty"},
Not empty или Must not be empty

2021-10-15 16:40 UTC, kullias approved these changes

2021-10-16 12:26 UTC, tsemashko approved these changes

2021-10-16 12:26 UTC, merged