Stage3
AMikhnyuk/study_project pull request #3
Opened 2021-10-20 13:26 UTC by AMikhnyuk

2021-10-20 17:43 UTC, tsemashko commented on sources/locales/en.js
> +	Save: "Save"
почему здесь меньше список, чем для ru ? в консоли warnings падают

2021-10-20 17:43 UTC, tsemashko commented on sources/views/activitiesViews/table.js
> +				return first <= obj.Date.getDate() && obj.Date.getDate() <= last;
неправильная логика для this week. проверь для даты 23 января 2019, тоже подпадёт под это условие, потому что здесь не учитывается ни месяц, ни год.

2021-10-20 17:43 UTC, tsemashko commented on sources/views/contacts.js
> +						.indexOf(value) !== -1);
по тз еще должна быть фильтрация по job, company, address, email, skype

2021-10-21 13:39 UTC, kullias requested changes

2021-10-21 13:39 UTC, kullias commented on sources/locales/ru.js
> +	"Activity Types": "Виды Активсностей ",
опечаточка

2021-10-21 13:39 UTC, kullias commented on sources/myapp.js
> +		app.use(plugins.Locale);
![Selection_999(324)](https://user-images.githubusercontent.com/31205423/138276427-9b06d11d-b618-4756-aa87-d9d14761c40d.png)
стоит подключить еще вебикс локали https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/plugins#combining-with-webix-locales

2021-10-21 13:39 UTC, kullias commented on sources/locales/ru.js
> +};
![Selection_999(325)](https://user-images.githubusercontent.com/31205423/138276797-52c02b3d-d541-46c1-98f9-407fe73bef92.png)

2021-10-21 13:39 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			if (value === _("Overdue")) return new Date(obj.DueDate) < d && obj.State === "Open";
не стоит полагаться на результат работы локализации как на айди в другой логике
отвалятся локали - отвалится это
кроме того - лишние вызовы переводчика
проще стоит опции определить как объекты с айди и вэлью

2021-10-21 13:39 UTC, kullias commented on sources/views/activitiesViews/table.js
> +		table.filter(obj => criteries(obj), "", true);
если открыть какую-то опцию из этих (например completed)
и начать добавлять/редактировать/чекать активити, данные остаются по старой фильтрации
стоит перефильтровывать, чтобы показывало актуальное

2021-10-21 13:39 UTC, kullias commented on sources/views/contacts.js
> +						.indexOf(value) !== -1);
а еще было бы лучше не копировать это все, а вынести в метод или функцию) а то выглядит пугающе

2021-10-21 13:39 UTC, kullias commented on sources/views/contacts.js
> +				});
еще фильтрация сбивается после операций (удаление, редактирование, добавление)
текст в инпуте остается, а фильтрация сбрасывается

2021-10-21 13:39 UTC, kullias commented on sources/views/settingsViews/tableConstructor.js
> +				{id: "Value", header: _("Value"), fillspace: true, editor: "text"},
редактирование какое-то непоследовательное получается
форма не позволяет оставить поля пустыми, зато эти эдиторы - да
![Selection_999(329)](https://user-images.githubusercontent.com/31205423/138281248-1385a0ae-5121-4785-952b-b4e92dc028e7.png)
самое простое что тут можно сделать - убрать эдиторы, раз есть форма
о том что есть эдиторы я вообще случайно например узнала (кликнула 2 раза)

2021-10-21 13:39 UTC, kullias commented on sources/views/settingsViews/tableConstructor.js
> +				{id: "Value", header: _("Value"), fillspace: true, editor: "text"},
кроме того, можно редактировать даже параллельно и открытая форма не обновляет свои значения (которые тем временем меняются через редактор)

2021-10-21 13:39 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			if (value === _("Tomorrow")) return d.getDate() === obj.Date.getDate() - 1;
The getDate() method returns the day of the month
то есть 21 октября сегодня и 22 ноября будет завтра?

2021-10-21 13:39 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			if (value === _("Tomorrow")) return d.getDate() === obj.Date.getDate() - 1;
у вебикса есть методы dayStart, add (с разными юнитами)

2021-10-21 13:39 UTC, kullias commented on sources/views/settingsViews/tableConstructor.js
> +			if(this.data.exists(formValues.id)){
if (formValues.id) 
там undefined вроде всегда в этом случае будет

2021-10-22 11:42 UTC, kullias commented on sources/views/contacts.js
> +		compare(obj.LastName));
LastName 2 раза (Address нету)

2021-10-22 11:42 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			if (id === "today") return d.getDate() === obj.Date.getDate();
![Screenshot from 2021-10-22 14-17-04](https://user-images.githubusercontent.com/31205423/138445055-1ef27ebd-b0fb-4fcb-b7d3-047f99e542a8.png)
getDate() возвращает число дня в месяце

2021-10-22 11:42 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			if (id === "tomorrow") return webix.Date.add(d, 1, "day", true).getDate() === obj.Date.getDate() && now();
можно несколько проще с датами 

еще до ветвления откинуть время от d (сегодняшней даты) и дальше с ней работать
откинуть время от даты активити 

для today сравнить даты или как числа (valueOf, неявное преобразование через +) или через вебиксовое апи (webix.Date.equal)
для tomorrow то же самое + от даты события отнять день при сравнении/или как тут у тебя добавить к сегодняшней
для week можно найти weekStart (вебиксовое апи) , weekEnd (прибавить 6 дней) и дату события сравнивать с ними через >= и <=
для month твой код сам по себе лаконичен и хорош

но now() - строго говоря не совпадает имя и то что ф-я делает (метод проверяет в этом ли месяце активити)

2021-10-25 09:09 UTC, kullias commented on sources/views/activitiesViews/table.js
> +				return first.getDate() <= o.getDate() &&
return first <= obj.Date && obj.Date <= last;
я потому и советовала использовать вебиксовое апи, чтобы самому не доставать число месяца, месяц и год

2021-10-25 09:09 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			function thisMonth() {
функции лучше внутри методов не определять
лучше:
- или выносить в функцию вне класса (если много функций одного типа собирается и если ты используешь их по разным модулям, можно выносить в отдельный модуль - просто файл с экспортируемыми функциями), 
- или если ф-я используется только одним модулем, то можно сделать методом класса

2021-10-25 09:09 UTC, kullias commented on sources/views/activitiesViews/table.js
>  		table.filter(obj => criteries(obj), "", true);
criteria (просто fyi)

2021-10-25 10:29 UTC, kullias approved these changes

2021-10-25 13:45 UTC, tsemashko approved these changes

2021-10-25 13:45 UTC, merged